## 1. How many Spam Emails are there?

In [134]:
def count_spam(path = "C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data", folders = ['enron1','enron2']):
    import os
    from pathlib import Path
    path = Path(path)
    spam_count = 0
    for folder in folders:
        file_names = os.listdir(path / folder / 'spam')
        for file_name in file_names:
            if 'spam' in file_name:
                spam_count += 1
    print('There are', spam_count, 'spam emails in', folders)

In [135]:
count_spam()

There are 2993 spam emails in ['enron1', 'enron2']


## 2. Structure the email data from the 2 directories into 1 dataframe with columns: Status, Subject, Body.

#### Specify the folders that will be included and the path leading to the folders.

In [136]:
folders = ['enron1','enron2']
status = ['spam','ham']
path1 = "C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\{folder}\\{status}"

#### Create the paths containing all the desired emails.

In [137]:
from itertools import product
directories = list(product(folders, status))
directories

[('enron1', 'spam'), ('enron1', 'ham'), ('enron2', 'spam'), ('enron2', 'ham')]

In [138]:
paths = []
for i in directories:
    paths.append(path1.format(folder=i[0],status=i[1]))
paths

['C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron2\\spam',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron2\\ham']

#### List all the files in each `path`.

In [139]:
import glob
file_paths = [glob.glob(pathname=path + '\\*') for path in paths]

#### Now we have all the file paths of the emails in the specified folders.

In [140]:
file_paths[0][0:5]

['C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam\\0006.2003-12-18.GP.spam.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam\\0008.2003-12-18.GP.spam.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam\\0017.2003-12-18.GP.spam.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam\\0018.2003-12-18.GP.spam.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\spam\\0026.2003-12-18.GP.spam.txt']

In [141]:
file_paths[1][0:5]

['C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham\\0001.1999-12-10.farmer.ham.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham\\0002.1999-12-13.farmer.ham.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham\\0003.1999-12-14.farmer.ham.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham\\0004.1999-12-14.farmer.ham.txt',
 'C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\apper-eda\\Notebooks\\data\\enron-data\\enron1\\ham\\0005.1999-12-14.farmer.ham.txt']

#### Having acquired the file paths, we can now extract the status, subject and message body of the emails.

In [142]:
subjects = []
bodies = []
status = []

# for each path
for file_path in file_paths:
    # for each file in path
    for i in file_path:
        # for status
        if 'spam.txt' in i:
            status.append('spam')
        elif 'ham.txt' in i:
            status.append('ham')
        # extract the subject from email
        with open(i,'r',errors='ignore') as f:
            subject = f.readlines()[0]
            subject = subject[9:]
            subjects.append(subject)
        # extract body message from email
        with open(i,'r',errors='ignore') as f:
            body = f.readlines()
            body = body[1:]
            bodies.append(body)
            
# join each sub-elements of the bodies list
bodies = [' '.join(i) for i in bodies]

print('Status has', len(status), 'elements.')
print('Subject has', len(subjects), 'elements.')
print('Body has', len(bodies), 'elements.')

Status has 11026 elements.
Subject has 11026 elements.
Body has 11026 elements.


In [153]:
spam = [1 if i == 'spam' else 0 for i in status]

#### Now, use the lists to create a dataframe.

In [143]:
import pandas as pd

In [164]:
enron = pd.DataFrame(list(zip(spam,subjects,bodies)), columns=['Spam','Subject','Body'])
enron.head(10)

Spam                                            Subject  \
0     1  dobmeos with hgh my energy level has gone up !...   
1     1        your prescription is ready . . oxwq s f e\n   
2     1                            get that new car 8434\n   
3     1                              await your response\n   
4     1  coca cola , mbna america , nascar partner with...   
5     1                               emerging small cap\n   
6     1               re : patchs work better then pillz\n   
7     1                    paliourg udtih 7 wcwknoanopkt\n   
8     1                real products for real people . b\n   
9     1  ^ . pe , nis s ^ ize mat ; ters ! yhvqbvdboevk...   

                                                Body  
0  introducing\n doctor - formulated\n hgh\n huma...  
1  low cost prescription medications\n soma , ult...  
2  people nowthe weather or climate in any partic...  
3  dear partner ,\n we are a team of government o...  
4  stock\n profile\n about\n company\n investment...  
5  to exit all additional mailings - - - >\n [ pr...  
6  worlds first dermal p ; atch technology for p ...  
7  good morning paliourg !\n last miraculous and ...  
8  dont waste your time at the doctors office !\n...  
9  briababhdpr frdjvdbesk cdpizacqjkufx hfkosxcym...

#### Save the dataframe as a `csv`.

In [165]:
enron.to_csv(path_or_buf="C:\\Users\\jakeedison.bersabe\\Cadetship\\EDA\\EDA-Projects\\PS3\\heron.csv", index=False, line_terminator='')

In [166]:
heron = pd.read_csv('heron.csv')

In [176]:
heron[['Spam']].value_counts()

Spam
0       8033
1       2993
dtype: int64

In [147]:
heron.shape

(11026, 3)

#### Import libraries for data cleaning.

In [177]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jakeedison.bersabe\AppData\Roaming\nltk_data.
[nltk_data]     ..
[nltk_data]   Package stopwords is already up-to-date!


#### Create the corpus.

In [218]:
ps = PorterStemmer() # extracts the root word of a word
all_stopwords = stopwords.words('english') # list of english stop words
all_stopwords.remove('not') # remove not from the stop words
corpus = []
for i in range(0, heron.shape[0]):
    body = re.sub(r'[^a-zA-Z]', ' ', str(heron['Body'][i])) # remove punctuations, replacing it with whitespace
    body = body.lower() # lower case everything
    body = body.split() 
    body = [ps.stem(word) for word in body if not word in set(all_stopwords)] # remove stopwords and extract root word
    body = ' '.join(body)
    corpus.append(body)

In [219]:
corpus[0]

'introduc doctor formul hgh human growth hormon also call hgh refer medic scienc master hormon plenti young near age twenti one bodi begin produc less time forti nearli everyon defici hgh eighti product normal diminish least advantag hgh increas muscl strength loss bodi fat increas bone densiti lower blood pressur quicken wound heal reduc cellulit improv vision wrinkl disappear increas skin thick textur increas energi level improv sleep emot stabil improv memori mental alert increas sexual potenc resist common ill strengthen heart muscl control cholesterol control mood swing new hair growth color restor read websit unsubscrib'

## Using `TfidfVectorizer`

In [232]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
tfid_vec = TfidfVectorizer(max_features=15000)
X = tfid_vec.fit_transform(corpus).toarray()
y = heron.iloc[:, 0].values

In [233]:
X.shape

(11026, 15000)

In [234]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [235]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [236]:
import numpy as np

In [237]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [238]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall score:", recall_score(y_test, y_pred))
print("Precision score:", precision_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred))

[[1558   57]
 [  32  559]]
Accuracy: 0.9596554850407978
Recall score: 0.9458544839255499
Precision score: 0.9074675324675324
F1 score: 0.9262634631317315


## Using `CountVectorizer`

In [227]:
cv = CountVectorizer(max_features=22000)
X = cv.fit_transform(corpus).toarray()
y = heron.iloc[:, 0].values

In [228]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [229]:
classifier_count = GaussianNB()
classifier_count.fit(X_train, y_train)

GaussianNB()

In [230]:
y_pred = classifier_count.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [231]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall score:", recall_score(y_test, y_pred))
print("Precision score:", precision_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred))

[[1594   21]
 [  99  492]]
Accuracy: 0.9456029011786038
Recall score: 0.8324873096446701
Precision score: 0.9590643274853801
F1 score: 0.8913043478260869
